version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    goamd64:
      - v2
      - v3

universal_binaries:
  - replace: true

release:
  github:
    owner: obaraelijah
    name: cirr

brews:
  - homepage: https://github.com/obaraelijah/homebrew-obaraelijah
    repository:
      owner: obaraelijah
      name: homebrew-obaraelijah

archives:
  - format_overrides:

    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"