version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X cmd.root.version={{.Version}}"

universal_binaries:
  - replace: true

release:
  github:
    owner: obaraelijah
    name: cirr

brews:
  - homepage: https://github.com/obaraelijah/homebrew-obaraelijah
    repository:
      owner: obaraelijah
      name: homebrew-obaraelijah

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"